---
version: 1.0.0.{build}
os:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017
build_script:
  - md _build
  - cd _build
  - cmake -A x64 -DOUTPUT_TIME_AND_POSITIONS:BOOL=OFF ..
  - ctest -VV -C Release -D Experimental .
test: off
